Task/tec 253/review rating logic
Luminescence-inc/Project-Delta-Backend pull request #70
Opened 2024-09-16 16:45 UTC by Benrobo

feat: Added reviews and ratings logic. Accounted for the following:

- Businesses shouldn't be able to review their own business
- Only verified users should leave a review. (created `isVerified` middleware)
- Prevented unauthorized users from deleting added reviews

2024-09-20 04:23 UTC, osxar requested changes

2024-09-20 04:23 UTC, osxar commented on server/src/schemas/reviewCreationRequest.schema.ts
> +    rating: z.number().int().min(1).max(5),
make this required

2024-09-20 04:23 UTC, osxar commented on server/src/controllers/business.controller.ts
> +          content: payload?.body?.content || '',
content isn't been parsed. maybe use a direct data type or interface instead of `export type ReviewCreationRequest = z.infer<typeof ReviewCreationRequestSchema>;`

2024-09-20 04:23 UTC, osxar commented on server/src/controllers/business.controller.ts
> +          rating: payload?.body?.rating,
rating isn't been parsed. maybe use a direct data type or interface instead of `export type ReviewCreationRequest = z.infer<typeof ReviewCreationRequestSchema>;`

2024-09-20 16:34 UTC, Benrobo commented on server/src/controllers/business.controller.ts
> +      await this.updateBusinessRatings(businessId);
ok

2024-09-20 16:35 UTC, Benrobo commented on server/src/controllers/business.controller.ts
> +    const business = await prisma.business_profiles.findUnique({
done

2024-09-20 16:37 UTC, Benrobo commented on server/src/schemas/reviewCreationRequest.schema.ts
> +    content: z.string().min(3).max(1000).optional(),
To prevent spamming.

2024-09-20 16:39 UTC, Benrobo commented on server/prisma/schema.prisma
> +  id          String   @id @default(dbgenerated("gen_random_uuid()")) @map("uuid") @db.Uuid
it still making use of uuid @osxar

2024-09-20 17:39 UTC, osxar commented on server/src/controllers/business.controller.ts
> +      if (!payload.content) {
remove this

2024-09-20 17:39 UTC, osxar commented on server/src/controllers/business.controller.ts
> +      if (!payload.rating) {
remove this

2024-09-24 00:06 UTC, osxar approved these changes

2024-09-24 00:07 UTC, merged